eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka

server:
  port: 8083

spring:
  application:
    name: cinema-ticket-service
  data:
    mongodb:
      host: localhost
      port: 27017
      database: cinema

